# Generated by Django 4.0.5 on 2022-06-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='service6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
    ]
