# Generated by Django 4.0.5 on 2022-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_service6'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='projectview/')),
            ],
        ),
    ]
