# Generated by Django 4.0.5 on 2022-06-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_mega67'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service6',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
