# Generated by Django 4.0.5 on 2022-06-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=400)),
                ('filter', models.TextField(max_length=100)),
                ('para', models.TextField(max_length=100)),
                ('headn', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='projectile/')),
            ],
        ),
    ]
