# Generated by Django 4.0.5 on 2022-06-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serve77',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameserve', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=800)),
                ('iconboxc', models.TextField(max_length=800)),
                ('dcode', models.TextField(max_length=800)),
                ('icondx', models.CharField(max_length=200)),
            ],
        ),
    ]
